export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOGOUT
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const LOGOUT = "LOGOUT";

export const ADD_GROCERY_ITEMS_REQUEST = "ADD_GROCERY_ITEMS_REQUEST";
export const ADD_GROCERY_ITEMS_SUCCESS = "ADD_GROCERY_ITEMS_SUCCESS";
export const ADD_GROCERY_ITEMS_FAILURE = "ADD_GROCERY_ITEMS_FAILURE";

export const GET_GROCERY_ITEMS_REQUEST = "GET_GROCERY_ITEMS_REQUEST";
export const GET_GROCERY_ITEMS_SUCCESS = "GET_GROCERY_ITEMS_SUCCESS";
export const GET_GROCERY_ITEMS_FAILURE = "GET_GROCERY_ITEMS_FAILURE";

export const CLEAR_GROCERY_ITEMS_REQUEST = "CLEAR_GROCERY_ITEMS_REQUEST";
export const CLEAR_GROCERY_ITEMS_SUCCESS = "CLEAR_GROCERY_ITEMS_SUCCESS";
export const CLEAR_GROCERY_ITEMS_FAILURE = "CLEAR_GROCERY_ITEMS_FAILURE";

export const DELETE_GROCERY_ITEMS_REQUEST = "DELETE_GROCERY_ITEMS_REQUEST";
export const DELETE_GROCERY_ITEMS_SUCCESS = "DELETE_GROCERY_ITEMS_SUCCESS";
export const DELETE_GROCERY_ITEMS_FAILURE = "DELETE_GROCERY_ITEMS_FAILURE";

export const UPDATE_GROCERY_ITEMS_REQUEST = "UPDATE_GROCERY_ITEMS_REQUEST";
export const UPDATE_GROCERY_ITEMS_SUCCESS = "UPDATE_GROCERY_ITEMS_SUCCESS";
export const UPDATE_GROCERY_ITEMS_FAILURE = "UPDATE_GROCERY_ITEMS_FAILURE";
